version: "3"
services:
  postgres:
    container_name: sample-db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

volumes:
  db-store:
